### ISSUE TITLE
'asyncpg.exceptions.UndefinedTableError'>: relation "user" does not exist

### ISSUE THREAD

**Issue by LarryEitel** [Kostiantyn-Salnykov/fastapi_quickstart#1]
I am playing with your project. I post to `http://localhost:8000/api/login` and I get:
```
sqlalchemy.exc.ProgrammingError: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedTableError'>: relation "user" does not exist
[SQL: INSERT INTO "user" (id, first_name, last_name, email, password_hash, status) VALUES (%s, %s, %s, %s, %s, %s) RETURNING "user".id, "user".created_at, "user".updated_at, "user".first_name, "user".last_name, "user".email, "user".password_hash, "user".status]
[parameters: (UUID('dfd59862-63af-4bc7-9c39-d8af83a651cf'), 'Larry', 'Smith', 'larry@example.com', '$2b$12$Ts5gutDgcKDE1lUeyilaz.1FYbZakSziqMWBnds9rYOQCYVnkNybq', 'UNCONFIRMED')]
```

Tests are all passing. :)

**Comment by LarryEitel** [comment]
Trying to Post new user to: /api/v1/users
```
uvicorn.error | httptools_impl.py:409 | run_asgi | ERROR | Exception in ASGI application
2022-11-15T21:10:39.731515706Z  | (2022-11-15T21:10:39Z/1668546639.7276683)
2022-11-15T21:10:39.731519866Z Traceback (most recent call last):
2022-11-15T21:10:39.731522036Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 404, in run_asgi
2022-11-15T21:10:39.731524186Z     result = await app(  # type: ignore[func-returns-value]
2022-11-15T21:10:39.731526186Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2022-11-15T21:10:39.731528166Z     return await self.app(scope, receive, send)
2022-11-15T21:10:39.731529916Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 86, in __call__
2022-11-15T21:10:39.731532036Z     raise exc from None
2022-11-15T21:10:39.731534056Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/uvicorn/middleware/message_logger.py", line 82, in __call__
2022-11-15T21:10:39.731535986Z     await self.app(scope, inner_receive, inner_send)
2022-11-15T21:10:39.731548796Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/fastapi/applications.py", line 270, in __call__
2022-11-15T21:10:39.731550846Z     await super().__call__(scope, receive, send)
2022-11-15T21:10:39.731552666Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/starlette/applications.py", line 124, in __call__
2022-11-15T21:10:39.731554466Z     await self.middleware_stack(scope, receive, send)
2022-11-15T21:10:39.731556196Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
2022-11-15T21:10:39.731558376Z     raise exc
2022-11-15T21:10:39.731560126Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
2022-11-15T21:10:39.731561996Z     await self.app(scope, receive, _send)
2022-11-15T21:10:39.731563676Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
2022-11-15T21:10:39.731565696Z     return await self.app(scope, receive, send)
2022-11-15T21:10:39.731568626Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
2022-11-15T21:10:39.731570526Z     await self.app(scope, receive, send)
2022-11-15T21:10:39.731572146Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/starlette/middleware/authentication.py", line 48, in __call__
2022-11-15T21:10:39.731573956Z     await self.app(scope, receive, send)
2022-11-15T21:10:39.731575605Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
2022-11-15T21:10:39.731577425Z     await responder(scope, receive, send)
2022-11-15T21:10:39.731579055Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 43, in __call__
2022-11-15T21:10:39.731580845Z     await self.app(scope, receive, self.send_with_gzip)
2022-11-15T21:10:39.731582565Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 75, in __call__
2022-11-15T21:10:39.731584375Z     raise exc
2022-11-15T21:10:39.731586055Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
2022-11-15T21:10:39.731587845Z     await self.app(scope, receive, sender)
2022-11-15T21:10:39.731589475Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
2022-11-15T21:10:39.731591395Z     raise e
2022-11-15T21:10:39.731593495Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
2022-11-15T21:10:39.731598475Z     await self.app(scope, receive, send)
2022-11-15T21:10:39.731600265Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 680, in __call__
2022-11-15T21:10:39.731602225Z     await route.handle(scope, receive, send)
2022-11-15T21:10:39.731603945Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 275, in handle
2022-11-15T21:10:39.731605705Z     await self.app(scope, receive, send)
2022-11-15T21:10:39.731608455Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 65, in app
2022-11-15T21:10:39.731610965Z     response = await func(request)
2022-11-15T21:10:39.731617165Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 231, in app
2022-11-15T21:10:39.731618975Z     raw_response = await run_endpoint_function(
2022-11-15T21:10:39.731620835Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
2022-11-15T21:10:39.731622665Z     return await dependant.call(**values)
2022-11-15T21:10:39.731624275Z   File "/backend/apps/users/routers.py", line 30, in create_user
2022-11-15T21:10:39.731625975Z     return await users_handler.create_user(request=request, session=session, data=data)
2022-11-15T21:10:39.731627735Z   File "/backend/apps/users/handlers.py", line 39, in create_user
2022-11-15T21:10:39.731629435Z     return UserOutSchema.from_orm(obj=user)  # type: ignore
2022-11-15T21:10:39.731631085Z   File "pydantic/main.py", line 577, in pydantic.main.BaseModel.from_orm
2022-11-15T21:10:39.731632785Z   File "pydantic/main.py", line 1055, in pydantic.main.validate_model
2022-11-15T21:10:39.731634515Z   File "pydantic/utils.py", line 441, in pydantic.utils.GetterDict.get
2022-11-15T21:10:39.731636325Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 482, in __get__
2022-11-15T21:10:39.731638125Z     return self.impl.get(state, dict_)
2022-11-15T21:10:39.731639735Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 942, in get
2022-11-15T21:10:39.731641505Z     value = self._fire_loader_callables(state, key, passive)
2022-11-15T21:10:39.731643155Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/attributes.py", line 978, in _fire_loader_callables
2022-11-15T21:10:39.731644985Z     return self.callable_(state, passive)
2022-11-15T21:10:39.731646595Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 912, in _load_for_state
2022-11-15T21:10:39.731650825Z     return self._emit_lazyload(
2022-11-15T21:10:39.731652535Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/strategies.py", line 1046, in _emit_lazyload
2022-11-15T21:10:39.731654375Z     result = session.execute(
2022-11-15T21:10:39.731656225Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1712, in execute
2022-11-15T21:10:39.731658065Z     result = conn._execute_20(statement, params or {}, execution_options)
2022-11-15T21:10:39.731659755Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
2022-11-15T21:10:39.731661545Z     return meth(self, args_10style, kwargs_10style, execution_options)
2022-11-15T21:10:39.731663205Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
2022-11-15T21:10:39.731665095Z     return connection._execute_clauseelement(
2022-11-15T21:10:39.731666765Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
2022-11-15T21:10:39.731668565Z     ret = self._execute_context(
2022-11-15T21:10:39.731670175Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
2022-11-15T21:10:39.731671985Z     self._handle_dbapi_exception(
2022-11-15T21:10:39.731674445Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2128, in _handle_dbapi_exception
2022-11-15T21:10:39.731676375Z     util.raise_(exc_info[1], with_traceback=exc_info[2])
2022-11-15T21:10:39.731678004Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
2022-11-15T21:10:39.731679924Z     raise exception
2022-11-15T21:10:39.731681504Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
2022-11-15T21:10:39.731683364Z     self.dialect.do_execute(
2022-11-15T21:10:39.731684974Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
2022-11-15T21:10:39.731686784Z     cursor.execute(statement, parameters)
2022-11-15T21:10:39.731688384Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 479, in execute
2022-11-15T21:10:39.731690424Z     self._adapt_connection.await_(
2022-11-15T21:10:39.731698614Z   File "/root/.cache/pypoetry/virtualenvs/fastapi-quickstart-yStQQXE7-py3.10/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 59, in await_only
2022-11-15T21:10:39.731701284Z     raise exc.MissingGreenlet(
2022-11-15T21:10:39.731702934Z sqlalchemy.exc.MissingGreenlet: greenlet_spawn has not been called; can't call await_only() here. Was IO attempted in an unexpected place? (Background on this error at: https://sqlalche.me/e/14/xd2s)
```

**Comment by LarryEitel** [comment]
I got past that error. I had to comment out the following:

```
class UserOutSchema(BaseOutSchema):
    id: uuid.UUID
    first_name: str = Field(title="First name", max_length=128, alias="firstName", example="John")
    last_name: str = Field(title="Last name", max_length=128, alias="lastName", example="Doe")
    email: Email = Field(title="Email", example="kostiantyn.salnykov@gmail.com")
    status: UsersStatuses = Field(default=UsersStatuses.UNCONFIRMED, title="User status", alias="status")
    created_at: Timestamp = Field(title="Created at", alias="createdAt")
    updated_at: Timestamp = Field(title="Updated at", alias="updatedAt")
    # groups: list[GroupOutSchema] | None = Field(default=[])
    # roles: list[RoleOutSchema] | None = Field(default=[])
    # permissions: list[PermissionOutSchema] | None = Field(default=[])
```

I started a test `users/test_services.py`:
```
import datetime
import uuid

import pytest
from faker import Faker
from sqlalchemy import delete
from sqlalchemy.ext.asyncio import AsyncSession

# from apps.users.enums import UserStatuses
from apps.users.models import User
from apps.users.schemas import UserCreateSchema, UserOutSchema, UserUpdateSchema, UserCreateToDBSchema
from apps.users.services import UserCRUDBase
from tests.apps.users.factories import UserFactory

from apps.CORE.managers import PasswordsManager
passwords_manager = PasswordsManager()

class TestUserCRUDBase:
    @classmethod
    def setup_class(cls):
        cls.service = UserCRUDBase(model=User)

    async def clear_users(self, session: AsyncSession):
        await session.execute(statement=delete(User))
        await session.commit()

    @staticmethod
    def check_uuid(field, expected_type: type = uuid.UUID) -> None:
        assert isinstance(field, expected_type)

    @staticmethod
    def check_datetime(field, expected_type: type = datetime.datetime) -> None:
        assert isinstance(field, expected_type)

    def check_defaults(self, obj):
        self.check_uuid(field=getattr(obj, "id"))
        self.check_datetime(field=getattr(obj, "created_at"))
        self.check_datetime(field=getattr(obj, "updated_at"))

    # async def test_list(self, faker: Faker, db_session: AsyncSession):
    #     await self.clear_users(session=db_session)
    #     users = await UserFactory.create_batch_async(size=faker.pyint(min_value=3, max_value=5))
    #
    #     total, users_list = await self.service.list(session=db_session, sorting=[])
    #
    #     assert total == len(users)
    #     assert [user.__repr__() for user in users_list] == [user.__repr__() for user in users]

    async def test_create(self, db_session: AsyncSession) -> None:
        equal_fields = {"first_name", "last_name"}
        user = UserCreateSchema(
            first_name="John",
            last_name="Doe",
            email="john@doe.com",
            password="asdfasdfasdfam"
        )
        create_to_db = UserCreateToDBSchema(
            **user.dict(by_alias=True, exclude={"password"}),
            password_hash=passwords_manager.make_password(password=user.password),
        )

        result = await self.service.create(session=db_session, obj=create_to_db)

        assert isinstance(result, User)
        result_schema = UserOutSchema.from_orm(obj=result)
        assert result_schema.dict(include=equal_fields) == user.dict(include=equal_fields)
        self.check_defaults(obj=result)


    #
    # async def test_read(self, db_session: AsyncSession) -> None:
    #     user: User = await UserFactory.create_async()
    #
    #     result: User = await self.service.read(session=db_session, id=user.id)
    #
    #     assert isinstance(result, User)
    #     assert result.id == user.id
    #     assert str(result) == str(user)
    #
    # async def test_read_none(self, faker: Faker, db_session: AsyncSession) -> None:
    #     fake_uuid = faker.uuid4(cast_to=None)
    #
    #     result = await self.service.read(session=db_session, id=fake_uuid)
    #
    #     assert result is None
    #
    # @pytest.mark.parametrize(
    #     argnames="status", argvalues=[UserStatuses.IN_WORK, UserStatuses.ARCHIVED, UserStatuses.COMPLETED]
    # )
    # async def test_update(self, faker: Faker, db_session: AsyncSession, status: UserStatuses) -> None:
    #     user: User = await UserFactory.create_async()
    #     new_title, new_description = faker.pystr(), faker.pystr()
    #     assert user.title != new_title
    #     assert user.description != new_description
    #     assert user.status != status
    #
    #     result: User = await self.service.update(
    #         session=db_session,
    #         id=user.id,
    #         obj=UserUpdateSchema(title=new_title, description=new_description, status=status),
    #     )
    #
    #     assert result.title == new_title
    #     assert result.description == new_description
    #     assert result.status == status
    #
    # async def test_delete(self, db_session: AsyncSession) -> None:
    #     user: User = await UserFactory.create_async()
    #
    #     result = await self.service.delete(session=db_session, id=user.id)
    #     assert result.rowcount == 1  # deleted one object from db
    #
    #     result2 = await self.service.delete(session=db_session, id=user.id)
    #     assert result2.rowcount == 0  # already deleted
```

Perhaps Authorization data needs to be initialized? Anyway, I like your implimentation!!!

**Comment by Kostiantyn-Salnykov** [comment]
@LarryEitel 
Thank you for contacting me 😄, I know about this problem (there is a problems with Factories at all), but I think I will try to fix all possible errors by meticulously testing the code in near future. After that I will make mkdocs material for this project (and HOWTOs)
Then it will already be possible to take it as a basic structure (in appropriate cases, as a replacement for Django).

At the moment the project has a purely educational base for my mentees and colleagues 😄

**Comment by LarryEitel** [comment]
@Kostiantyn-Salnykov 

Thank you for your reply. I think that you will appreciate knowing that while analyzing MANY - perhaps hundreds of FastAPI-related repos - I view your project one of the best implementations. I - we - appreciate any efforts to continue improving it.

**Comment by Kostiantyn-Salnykov** [comment]
Hello @LarryEitel, I've pushed new updates to the repository, there are many changes to fix possible problems (and many interesting new ones (like multiple sorting and filtering concepts.

But I didn't touch tests (many of them should fail now). I'll resolve factories after I complete the `authorization` app and all related routers, handlers, and services.

Also in near future write a small setup guide to this repo (maybe will help other people to learn the codebase internally).
